// Shared site data for kuni88.github.io
// Loaded as a plain <script> before any Babel/React scripts.

window.PROFILE = {
  name: { en: "Kunihiro Takeoka", ja: "竹岡 邦紘" },
  handle: "kuni88",
  role: { en: "Senior Principal Researcher", ja: "主幹研究員" },
  org: { en: "NEC Corporation — Data Science Laboratory", ja: "NEC データサイエンスラボラトリー" },
  location: "Tokyo, Japan",
  status: {
    en: "active · building cotomi Act · open to collab",
    ja: "稼働中 · cotomi Act 開発 · 共同研究歓迎",
  },
  mission: {
    en: "A world where people can focus on the work they want to do.",
    ja: "やりたい仕事に集中できる世界に",
  },
  now: {
      en: [
	  "Building Agentic AI, cotomi Act",
	  "Building NEC's cotomi LLM series",
	  "LLM-based retrieval & recommendation",
    ],
      ja: [
	  "Agentic AI 'cotomi Act' の開発",
	  "NECのLLM (cotomi) シリーズの開発",
	  "LLM を活用した検索・推薦",
    ],
  },
  interests: {
    en: ["Machine Learning", "NLProc", "Human-Computer Interaction", "Information Retrieval"],
    ja: ["機械学習", "自然言語処理", "HCI", "情報検索"],
  },
  education: [
    { degree_en: "MEng, Computer Science", degree_ja: "修士(工学)、情報科学", year: "2018", school_en: "Kwansei Gakuin University", school_ja: "関西学院大学" },
    { degree_en: "BSc, Computer Science",  degree_ja: "学士(工学)、情報科学", year: "2016", school_en: "Kwansei Gakuin University", school_ja: "関西学院大学" },
  ],
};

window.PUBLICATIONS = [
  {
    id: "kusano-2025-recsys", slug: "kusano-2025-recsys",
    venue: "RecSys 2025", year: 2025, month: "Sep",
    authors: ["Genki Kusano", "Kosuke Akimoto", "Kunihiro Takeoka"],
    title: "Revisiting Prompt Engineering: A Comprehensive Evaluation for LLM-based Personalized Recommendation",
    tag: "LLM · RecSys", icon: "sparkle",
    url: "/publication/kusano-2025-recsys/",
    summary_en: "Systematic evaluation of prompt design choices for LLM-based personalized recommendation across multiple prompting setups.",
    summary_ja: "LLM ベースの個別化推薦に対して、複数のプロンプト設計を体系的に比較評価した研究です。",
    pdf_url: "https://dblp.org/rec/conf/recsys/KusanoAT25.html",
  },
  {
    id: "abe-2025-sigir", slug: "abe-2025-sigir",
    venue: "SIGIR 2025", year: 2025, month: "Jul",
    authors: ["Kenya Abe", "Kunihiro Takeoka", "Makoto P. Kato", "Masafumi Oyamada"],
    title: "LLM-based Query Expansion Fails for Unfamiliar and Ambiguous Queries",
    tag: "IR · LLM", icon: "search",
    url: "/publication/abe-2025-sigir/",
    summary_en: "Analyzes when LLM-based query expansion breaks down, especially for unfamiliar or ambiguous search intents.",
    summary_ja: "LLM によるクエリ拡張が、未知語や曖昧な検索意図に対して失敗しやすい条件を分析した研究です。",
    pdf_url: "https://dblp.org/rec/conf/sigir/AbeTKO25.html",
  },
  {
    id: "yano-2024-naacl", slug: "yano-2024-naacl",
    venue: "SEM@NAACL 2024", year: 2024, month: "Jun",
    authors: ["Taro Yano", "Kunihiro Takeoka", "Masafumi Oyamada"],
    title: "Relevance, Diversity, and Exclusivity: Designing Keyword-augmentation Strategy for Zero-shot Classifiers",
    tag: "NLProc", icon: "tag",
    url: "/publication/yano-2024-naacl/",
    summary_en: "Studies how relevance, diversity, and exclusivity affect keyword augmentation for zero-shot text classification.",
    summary_ja: "ゼロショット分類向けのキーワード拡張で、関連性・多様性・排他性の設計が与える影響を調べた研究です。",
    pdf_url: "https://dblp.org/rec/conf/naacl/YanoTO24.html",
  },
  {
    id: "akimoto-2023-emnlp", slug: "akimoto-etal-2023-context",
    venue: "EMNLP 2023", year: 2023, month: "Dec",
    authors: ["Kosuke Akimoto", "Kunihiro Takeoka", "Masafumi Oyamada"],
    title: "Context Quality Matters in Training Fusion-in-Decoder for Extractive Open-Domain Question Answering",
    tag: "NLProc · QA", icon: "question",
    url: "/publication/akimoto-etal-2023-context/",
    summary_en: "Shows that the quality of retrieved contexts strongly influences FiD training for open-domain extractive QA.",
    summary_ja: "オープンドメイン質問応答における FiD 学習では、検索コンテキストの質が性能を大きく左右することを示した研究です。",
    pdf_url: "https://aclanthology.org/2023.findings-emnlp.784/",
    bib: true,
  },
  {
    id: "takeoka-2021-emnlp", slug: "takeoka-etal-2021-low",
    venue: "EMNLP 2021", year: 2021, month: "Nov",
    authors: ["Kunihiro Takeoka", "Kosuke Akimoto", "Masafumi Oyamada"],
    title: "Low-resource Taxonomy Enrichment with Pretrained Language Models",
    tag: "NLProc", icon: "tree",
    url: "/publication/takeoka-etal-2021-low/",
    summary_en: "Proposes a pretrained-language-model approach to expand taxonomies under limited labeled resources.",
    summary_ja: "少ない教師データしかない状況で、事前学習言語モデルを使ってタクソノミーを拡張する手法を提案した研究です。",
    image: "/publication/takeoka-etal-2021-low/featured.png",
    pdf_url: "https://aclanthology.org/2021.emnlp-main.217/",
    bib: true,
  },
  {
    id: "enomoto-2021-pakdd", slug: "enomoto-2021-quality",
    venue: "PAKDD 2021", year: 2021, month: "May",
    authors: ["Masafumi Enomoto", "Kunihiro Takeoka", "Yuyang Dong", "Masafumi Oyamada", "Takeshi Okadome"],
    title: "Quality Control for Hierarchical Classification with Incomplete Annotations",
    tag: "ML", icon: "tag",
    url: "/publication/enomoto-2021-quality/",
    summary_en: "Addresses reliability control in hierarchical classification when training data has incomplete annotations.",
    summary_ja: "不完全なアノテーションを含む学習データに対して、階層分類の品質管理を扱った研究です。",
    bib: true,
  },
  {
    id: "dong-2021-icde", slug: "dong-2021-efficient",
    venue: "ICDE 2021", year: 2021, month: "Apr",
    authors: ["Yuyang Dong", "Kunihiro Takeoka", "Chuan Xiao", "Masafumi Oyamada"],
    title: "Efficient Joinable Table Discovery in Data Lake: A High-Dimensional Similarity-Based Approach",
    tag: "Data", icon: "search",
    url: "/publication/dong-2021-efficient/",
    summary_en: "Introduces a similarity-based method for efficiently finding joinable tables in large data lakes.",
    summary_ja: "大規模データレイクから結合可能なテーブルを効率よく見つける類似度ベース手法を提案した研究です。",
    pdf_url: "https://link.springer.com/chapter/10.1007/978-3-030-75768-7_18",
    bib: true,
  },
  {
    id: "dong-2020-vldb", slug: "dong-2020-continuous",
    venue: "VLDB Journal 2020", year: 2020, month: "Nov",
    authors: ["Yuyang Dong", "Chuan Xiao", "Hanxiong Chen", "Jefferey Xu Yu", "Kunihiro Takeoka", "Masafumi Oyamada", "Hiroyuki Kitagawa"],
    title: "Continuous top-k spatial–keyword search on dynamic objects",
    tag: "DB · IR", icon: "search",
    url: "/publication/dong-2020-continuous/",
    summary_en: "Presents continuous top-k spatial-keyword search techniques for moving objects in dynamic environments.",
    summary_ja: "動的に移動する対象に対する、継続的な top-k 空間キーワード検索を扱った研究です。",
    pdf_url: "https://link.springer.com/article/10.1007/s00778-020-00627-4",
    doi_url: "https://doi.org/10.1007/s00778-020-00627-4",
    bib: true,
  },
  {
    id: "takeoka-2020-aaai", slug: "aaai-2020-unsure",
    venue: "AAAI 2020", year: 2020, month: "Feb",
    authors: ["Kunihiro Takeoka", "Yuyang Dong", "Masafumi Oyamada"],
    title: "Learning with Unsure Responses",
    tag: "ML", icon: "question",
    url: "/publication/aaai-2020-unsure/",
    summary_en: "Explores how to train models effectively when annotations include unsure responses instead of hard labels.",
    summary_ja: "確信のない回答を含むアノテーション環境で、学習をどう安定化させるかを扱った研究です。",
    image: "/publication/aaai-2020-unsure/featured.png",
    pdf_url: "https://aaai.org/ojs/index.php/AAAI/article/view/5355",
    doi_url: "https://doi.org/10.1609/aaai.v34i01.5355",
    bib: true,
  },
  {
    id: "takeoka-2019-aaai", slug: "aaai-2019-meimei",
    venue: "AAAI 2019", year: 2019, month: "Jan",
    authors: ["Kunihiro Takeoka", "Masafumi Oyamada", "Shinji Nakadai", "Takeshi Okadome"],
    title: "Meimei: An Efficient Probabilistic Approach for Semantically Annotating Tables",
    tag: "Data · NLProc", icon: "sparkle",
    url: "/publication/aaai-2019-meimei/",
    summary_en: "Proposes an efficient probabilistic framework for semantic annotation of tabular data.",
    summary_ja: "表データに対する意味アノテーションを効率的に行う確率的アプローチを提案した研究です。",
    image: "/publication/aaai-2019-meimei/featured.png",
    pdf_url: "https://doi.org/10.1609/aaai.v33i01.3301281",
    bib: true,
  },
];

window.PROJECTS = [
  {
    id: "cotomi-act", slug: "cotomi-act", year: 2026, icon: "bot",
    title_en: "cotomi Act Development",  title_ja: "cotomi Act 開発",
    desc_en: "Developing NEC's agent technology for continuous automation of digital operations.",
    desc_ja: "デジタル業務の継続的な自動化を実現するNECのエージェント技術を開発。",
    body_en: "cotomi Act is NEC's agent technology for automating digital operations that require judgment and adaptive responses, such as expense reimbursement, order processing, and screening workflows. According to NEC's December 3, 2025 press release, the solution automatically extracts operational know-how from browser histories and action logs, turns it into organizational assets, and uses that knowledge to drive safe and reliable automation at scale.",
    body_ja: "cotomi Act は、経費精算、受発注、審査業務のように、判断や臨機応変な対応が求められるデジタル業務を自動化するための NEC のエージェント技術です。2025年12月3日の NEC 公式プレスリリースでは、ブラウザ上の閲覧履歴や操作ログから業務ノウハウを自動抽出して組織資産化し、その知識を用いて安全・安心に業務自動化を継続的に推進するソリューションとして説明されています。",
    tag: "Agentic AI, automation", url: "https://jpn.nec.com/press/202512/20251203_01.html",
  },
  {
    id: "deep-research-agent", slug: "deep-research-agent", year: 2025, icon: "search",
    title_en: "Deep Research Agent Development",  title_ja: "Deep Research Agent 開発",
    desc_en: "Developing an agentic system that autonomously searches, cites sources, and drafts reports.",
    desc_ja: "自律的に情報探索・出典提示・レポート作成を行う Agentic AI システムを開発。",
    body_en: "This project focuses on NEC's agentic AI for information gathering and report drafting. NEC's May 22, 2025 R&D article describes a system that accepts a user goal, plans the required subtasks, searches across the web and internal sites, presents sources for verification, and supports enterprise deployment including on-premises environments. The technical foundation combines know-how from cotomi LLM development, hybrid task decomposition, and source-grounded answer generation.",
    body_ja: "本プロジェクトは、情報収集とレポート作成に特化した NEC の Agentic AI の開発です。2025年5月22日の NEC R&D 記事では、ユーザがゴールを与えるだけで、必要なタスクを分解し、Web や社内サイトを自律的に探索し、参照元を提示しながら回答やレポートを生成するシステムとして紹介されています。技術的には、cotomi の LLM 開発で培ったノウハウ、ハイブリッドなタスク分解アルゴリズム、出典付き回答を実現する設計が基盤になっています。",
    tag: "Agentic AI, research", url: "https://jpn.nec.com/rd/technologies/202502/index.html",
  },
  {
    id: "cotomi-llm", slug: "cotomi-llm", year: 2023, icon: "sparkle",
    title_en: "cotomi LLM Development",  title_ja: "LLM開発 (cotomi)",
    desc_en: "Building NEC's LLM and generative AI core technology for enterprise use.",
    desc_ja: "エンタープライズ利用に向けた NEC の LLM / 生成AI コア技術を開発。",
    body_en: "cotomi is NEC's AI core technology and the foundation of its generative AI offerings. NEC describes cotomi as a high-speed, high-performance, and flexibly deployable enterprise AI stack, with continued expansion in agent capabilities, MCP support, longer context windows, and multimodal document handling. This project covers the development of the cotomi LLM series and its application to real business workflows.",
    body_ja: "cotomi は、NEC が開発する AI コア技術であり、生成AIサービスの中核を担う基盤です。NEC の公式ページでは、高速・高性能・豊富な提供形態を特長とするエンタープライズ向け生成AIとして説明されており、エージェント性能の強化、MCP 対応、長文コンテキスト対応、マルチモーダル資料活用なども拡張されています。本プロジェクトでは、cotomi シリーズの LLM 開発と、それを実業務へ適用するための基盤整備に取り組んでいます。",
    tag: "LLM", url: "https://jpn.nec.com/LLM/cotomi.html",
  },
  {
    id: "aio3", slug: "aio3rd", year: 2022, icon: "trophy",
    title_en: "1st place — AIO 3rd",  title_ja: "1位 — AIO 第3回",
    desc_en: "Japanese Quiz AI Competition 2022 champion with team Revo.",
    desc_ja: "チーム Revo として日本語クイズAIコンペ2022で優勝。",
    body_en: "Our team Revo (Takeoka, Akimoto, Hayashi, and Oyamada) won 1st place in AI王 (AI-Ō) 3rd competition, a Japanese Quiz AI competition held in 2022. The competition tested systems on open-domain question answering over Japanese trivia questions. We built a retrieval-augmented QA pipeline combining dense retrieval and cross-encoder reranking, achieving the highest accuracy among all teams.",
    body_ja: "チーム Revo（竹岡・秋本・林・小山田）として、2022年開催の日本語クイズAIコンペ「AI王 第3回」で1位を獲得しました。コンペは日本語の一般知識問題に対するオープンドメイン質問応答システムを競うものでした。密なベクトル検索とクロスエンコーダーによるリランキングを組み合わせた検索拡張型QAパイプラインを構築し、全チーム中最高精度を達成しました。",
    tag: "NLProc, competition", url: "https://sites.google.com/view/project-aio/competition3/final-presentation",
    image: "/project/aio3rd/featured.png",
  },
  {
    id: "aio2", slug: "aio2nd", year: 2022, icon: "trophy",
    title_en: "1st place — AIO 2nd",  title_ja: "1位 — AIO 第2回",
    desc_en: "Japanese Quiz AI Competition 2021–2022 champion.",
    desc_ja: "日本語クイズAIコンペ2021–2022で優勝。",
    body_en: "Our team Revo (Akimoto & Takeoka) won 1st place in AI王 (AI-Ō) 2nd competition, a Japanese Quiz AI competition spanning 2021–2022. We developed a retrieval-based QA system leveraging BERT-based dense retrieval and a cross-encoder reranker over a large Japanese Wikipedia corpus. The system outperformed all other teams in the final evaluation.",
    body_ja: "チーム Revo（秋本・竹岡）として、2021–2022年開催の日本語クイズAIコンペ「AI王 第2回」で1位を獲得しました。BERTベースの密ベクトル検索とクロスエンコーダーによるリランキングを日本語Wikipediaコーパスに適用したQAシステムを開発し、最終評価で全チームを上回りました。",
    tag: "NLProc, competition", url: "/project/aio2nd/",
    image: "/project/aio2nd/featured.png",
  },
  {
    id: "yotta", slug: "yotta_free", year: 2021, icon: "wine",
    title_en: "Yotta Free",  title_ja: "Yotta Free",
    desc_en: "A Mac app that makes you look drunk. Playful HCI hackathon project.",
    desc_ja: "ユーザを酔っぱらった風に見せるMacアプリ。遊び心のあるHCIハッカソン作品。",
    body_en: "Yotta Free is a Mac app that applies a real-time drunk visual effect to your FaceTime or video call feed. Built as a hackathon project for the HCI course, it uses macOS screen capture and Core Image filters to simulate the blurred, wobbly vision associated with intoxication. A tongue-in-cheek exploration of presence manipulation in video communication.",
    body_ja: "Yotta Free は、FaceTime やビデオ通話の映像にリアルタイムで「酔っぱらい風エフェクト」を適用するMacアプリです。HCI演習のハッカソン課題として制作し、macOS のスクリーンキャプチャと Core Image フィルターを使用して、ぼやけや揺れのある映像を生成します。ビデオコミュニケーションにおける「存在感の操作」という視点からの遊び心のある探求です。",
    tag: "HCI, macOS", url: "/project/yotta_free/",
    image: "/project/yotta_free/featured.jpeg",
    video_url: "https://youtu.be/lXl-brlEuRw?t=8751",
  },
  {
    id: "insticker", slug: "insticker", year: 2019, icon: "sticker",
    title_en: "Insticker",  title_ja: "Insticker",
    desc_en: "Instantly generate a sticker from a word and your emotion.",
    desc_ja: "対象語と感情から即興でステッカーを生成するシステム。",
    body_en: "Insticker is a system for instantly generating a sticker from a target word and an emotion label. The user inputs a keyword (e.g., \"cat\") and selects an emotion (e.g., \"angry\"), and the system synthesizes an expressive sticker image by combining image retrieval and style transfer. Demonstrated at HCI conference.",
    body_ja: "Insticker は、対象語と感情ラベルから即興でステッカーを生成するシステムです。ユーザーがキーワード（例：「猫」）と感情（例：「怒り」）を入力すると、画像検索とスタイル転送を組み合わせて表情豊かなステッカー画像を合成します。HCI系学会にて発表。",
    tag: "HCI, generation", url: "/project/insticker/",
    image: "/project/insticker/featured.jpg",
    video_url: "https://youtu.be/HNjXZwRTybU?t=10743",
  },
  {
    id: "helloworld", slug: "hello-world", year: 2016, icon: "code",
    title_en: "HELLO WORLD!",  title_ja: "HELLO WORLD!",
    desc_en: "Web app for online pair programming and video communication.",
    desc_ja: "オンラインペアプログラミングと映像通信のWebアプリ。",
    body_en: "HELLO WORLD! is a web application for online pair programming with real-time video communication. It provides a shared code editor with syntax highlighting and a peer video window side by side, enabling remote collaborators to code together as if sitting next to each other. Built during undergraduate years as an exploration of real-time collaborative tools.",
    body_ja: "HELLO WORLD! は、リアルタイム映像通信付きのオンラインペアプログラミング用Webアプリです。シンタックスハイライト付きの共有コードエディタとピアビデオウィンドウを並べて提供し、離れた場所にいる共同作業者が隣に座っているかのようにコードを書けます。学部時代にリアルタイム協調ツールの探求として制作しました。",
    tag: "collab,  web, coding", url: "/project/hello-world/",
    image: "/project/hello-world/featured.png",
  },
];

window.EXPERIENCE = [
  {
    title_en: "Senior Principal Researcher", title_ja: "主幹研究員",
    org: "NEC Corporation", start: "2026-04", end: null,
    notes_en: "Technical lead of cotomi Act team.",
    notes_ja: "cotomi Act チームのテクニカルリード",
    url: null,
  },
  {
    title_en: "Principal Researcher", title_ja: "主任研究員",
    org: "NEC Corporation", start: "2024-04", end: "2026-03",
    notes_en: "NLProc & information retrieval. Joining LLM dev team (cotomi series).",
    notes_ja: "自然言語処理と情報検索。LLM 開発(cotomi シリーズ)に参画",
    url: "https://jpn.nec.com/LLM/cotomi.html",
  },
  {
    title_en: "Special Researcher", title_ja: "特別研究員",
    org: "NEC Corporation", start: "2021-04", end: "2024-03",
    notes_en: "NLProc and information extraction.",
    notes_ja: "自然言語処理と情報抽出",
    url: null,
  },
  {
    title_en: "Researcher", title_ja: "研究員",
    org: "NEC Corporation", start: "2018-04", end: "2021-03",
    notes_en: "Data profiling and machine learning.",
    notes_ja: "データプロファイリングと機械学習",
    url: "https://jpn.nec.com/rd/technologies/201906/index.html",
  },
  {
    title_en: "Researcher (Intern)", title_ja: "研究員(インターン)",
    org: "ABEJA Inc.", start: "2016-09", end: "2016-09",
    notes_en: "Deep learning for computer vision.",
    notes_ja: "コンピュータビジョンのための深層学習",
    url: null,
  },
  {
    title_en: "Researcher (Intern)", title_ja: "研究員(インターン)",
    org: "NEC Corporation", start: "2016-07", end: "2016-08",
    notes_en: "Data profiling: DB systems × NLrocP × ML.",
    notes_ja: "データプロファイリングの研究: 機械学習のデータベース分野への応用",
    url: "https://archive.dbsj.org/dbjapan/2016/msg00211.html",
  },
];

window.LINKS = [
  { label: "github",  icon: "github",  url: "https://github.com/Kuni88" },
  { label: "scholar", icon: "scholar", url: "https://scholar.google.co.jp/citations?user=A5N_jNsAAAAJ" },
  { label: "dblp",    icon: "dblp",    url: "https://dblp.org/pid/180/8519.html" },
  { label: "twitter", icon: "twitter", url: "https://twitter.com/_kuni88" },
  { label: "email",   icon: "mail",    url: "mailto:kunihiro.takeoka.93+contact@gmail.com" },
];

window.ACCENT_MAP = {
  purple: { light: ["#6d28d9","#ede9fe","#4c1d95"], dark: ["#a78bfa","#3b2d6e","#c4b5fd"] },
  indigo: { light: ["#4338ca","#e0e7ff","#312e81"], dark: ["#818cf8","#2d2a6e","#a5b4fc"] },
  blue:   { light: ["#1d4ed8","#dbeafe","#1e3a8a"], dark: ["#60a5fa","#1e3a5f","#93c5fd"] },
  green:  { light: ["#16a34a","#dcfce7","#14532d"], dark: ["#4ade80","#14532d","#86efac"] },
  amber:  { light: ["#d97706","#fef3c7","#92400e"], dark: ["#fbbf24","#451a03","#fde68a"] },
};
